// <auto-generated />
using A2_updated_p1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A2_updated_p1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231115162123_InitialWithCategoriesTable")]
    partial class InitialWithCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A2_updated_p1.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "coding",
                            Name = "Coding"
                        },
                        new
                        {
                            CategoryId = "history",
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = "gadgets",
                            Name = "Gadgets"
                        },
                        new
                        {
                            CategoryId = "science",
                            Name = "Science"
                        },
                        new
                        {
                            CategoryId = "travel",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = "movies",
                            Name = "Movies"
                        },
                        new
                        {
                            CategoryId = "health",
                            Name = "Health"
                        },
                        new
                        {
                            CategoryId = "sports",
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryId = "music",
                            Name = "Music"
                        },
                        new
                        {
                            CategoryId = "food",
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("A2_updated_p1.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("A2_updated_p1.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("A2_updated_p1.Models.FAQ", b =>
                {
                    b.HasOne("A2_updated_p1.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A2_updated_p1.Models.Topic", "Topic")
                        .WithMany("FAQs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("A2_updated_p1.Models.Topic", b =>
                {
                    b.HasOne("A2_updated_p1.Models.Category", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("A2_updated_p1.Models.Category", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("A2_updated_p1.Models.Topic", b =>
                {
                    b.Navigation("FAQs");
                });
#pragma warning restore 612, 618
        }
    }
}
